### ISSUE TITLE
while bundling getting errors

### ISSUE THREAD

**Issue by chetantete** [Apollo-IT/peatio_current#3]
trying to setup peatio of this branch on Ubuntu  17.04
as given with ruby 2.2.8
but getting error 
Fetching nokogiri 1.8.2
Installing nokogiri 1.8.2 with native extensions
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

    current directory: /home/.rvm/gems/ruby-2.2.8/gems/nokogiri-1.8.2/ext/nokogiri
/home/.rvm/rubies/ruby-2.2.8/bin/ruby -r ./siteconf20180404-3891-w83q4z.rb extconf.rb --use-system-libraries
checking if the C compiler accepts ... yes
Building nokogiri using system libraries.
checking for xmlParseDoc() in libxml/parser.h... yes
checking for xsltParseStylesheetDoc() in libxslt/xslt.h... yes
checking for exsltFuncRegister() in libexslt/exslt.h... yes
checking for xmlHasFeature()... yes
checking for xmlFirstElementChild()... yes
checking for xmlRelaxNGSetParserStructuredErrors()... yes
checking for xmlRelaxNGSetParserStructuredErrors()... yes
checking for xmlRelaxNGSetValidStructuredErrors()... yes
checking for xmlSchemaSetValidStructuredErrors()... Aborted (core dumped)

To see why this extension failed to compile, please check the mkmf.log which can be found here:

  /home/.rvm/gems/ruby-2.2.8/extensions/x86_64-linux/2.2.0/nokogiri-1.8.2/mkmf.log

extconf failed, exit code 134

Gem files will remain installed in /home/.rvm/gems/ruby-2.2.8/gems/nokogiri-1.8.2 for inspection.
Results logged to /home/.rvm/gems/ruby-2.2.8/extensions/x86_64-linux/2.2.0/nokogiri-1.8.2/gem_make.out

**Comment by Apollo-IT** [comment]
hi, This repository is WIP.
it's under upgrading.
It will be completed soon.
Until that, we can meet some issues.
